version: "3.8"

services:
  registry:
    image: registry:2
    networks:
      - traefik_proxy
    environment:
      - REGISTRY_HTTP_ADDR=:443
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - ./registry:/var/lib/registry
      - ./config/config.yml:/etc/docker/registry/config.yml
      - ./certs/wildcard.crt:/certs/wildcard.crt:ro
      - ./certs/wildcard.key:/certs/wildcard.key:ro
    deploy:
      placement:
        constraints:
          - node.hostname == growlithe
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"
        - "traefik.http.routers.registry.rule=Host(`registry.itslit`)"
        - "traefik.http.services.registry.loadbalancer.server.port=443"
        - "traefik.http.routers.registry.entrypoints=websecure"
        - "traefik.http.routers.registry.tls=true"
        - "traefik.http.routers.registry.service=registry"

  registry_mirror:
    image: docker:27.3.1
    command: ["/bin/sh", "-c", "apk add --no-cache jq curl && /scripts/mirror-images.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../Scripts/mirror-images.sh:/scripts/mirror-images.sh:ro
      - ./certs/wildcard.crt:/usr/local/share/ca-certificates/wildcard.crt:ro
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.hostname == growlithe
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 2 * * *"
        - "swarm.cronjob.skip-running=true"
    networks:
      - traefik_proxy
  registry_gc:
    image: docker:27.3.1
    command: ["/bin/sh", "-c", "apk add --no-cache bash && /scripts/registry-cleanup.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../Scripts/registry-cleanup.sh:/scripts/registry-cleanup.sh:ro
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.hostname == growlithe
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 3 * * 0"   # Every Sunday at 03:00
        - "swarm.cronjob.skip-running=true"
    networks:
      - traefik_proxy


networks:
  traefik_proxy:
    attachable: true
    external: true
