version: "3.8"

services:
  registry:
    image: registry:2
    networks:
      - traefik_proxy
    volumes:
      - /mnt/data/registry:/var/lib/registry
    deploy:
      placement:
        constraints:
          - node.hostname == growlithe
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registry.rule=Host(`registry.itslit`)"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
        - "traefik.http.routers.registry.entrypoints=websecure"
        - "traefik.http.routers.registry.tls=true"
        #- "traefik.http.routers.registry.tls.certresolver=selfsigned"
        - "traefik.http.routers.registry.service=registry"

networks:
  traefik_proxy:
    driver: overlay
    attachable: true
