version: "3.8"

services:
  registry:
    image: registry:2
    networks:
      - traefik_proxy
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/local.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/local.key
    volumes:
      - ./registry:/var/lib/registry
      - ./config/config.yml:/etc/docker/registry/config.yml
      - ../Traefik/certs:/certs:ro
    deploy:
      placement:
        constraints:
          - node.hostname == growlithe
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"
        - "traefik.http.routers.registry.rule=Host(`registry.itslit`)"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
        - "traefik.http.routers.registry.entrypoints=websecure"
        - "traefik.http.routers.registry.tls=true"
        - "traefik.http.routers.registry.service=registry"
networks:
  traefik_proxy:
    attachable: true
    external: true
