version: "3.8"

services:
  registry:
    image: registry:2
    networks:
      - traefik-public
    volumes:
      - /mnt/data/registry:/var/lib/registry
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registry.rule=Host(`registry.itslit`)"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
        - "traefik.http.routers.registry.entrypoints=web"
        - "traefik.http.routers.registry.service=registry"

networks:
  traefik-public:
    external: true
