version: "3.8"

services:
  registry:
    image: registry:2
    networks:
      - traefik_proxy
    environment:
      - REGISTRY_HTTP_ADDR=:5000
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - ./registry:/var/lib/registry
      - ./config/config.yml:/etc/docker/registry/config.yml
    deploy:
      placement:
        constraints:
          - node.hostname == growlithe
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"
        - "traefik.http.routers.registry.rule=Host(`registry.itslit`)"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
        - "traefik.http.routers.registry.entrypoints=websecure"
        - "traefik.http.routers.registry.tls=true"
        - "traefik.http.routers.registry.service=registry"

  registry_mirror:
    image: docker:27.3.1
    command: ["/bin/sh", "-c", "/scripts/mirror-images.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../Scripts/mirror-images.sh:/scripts/mirror-images.sh:ro
    deploy:
      placement:
        constraints:
          - node.hostname == growlithe
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 2 * * *"  # nightly at 02:00
        - "swarm.cronjob.skip-running=true"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    attachable: true
    external: true
