route:
  receiver: 'email'
  repeat_interval: 4h
  group_by: [alertname]

receivers:
  - name: 'email'
    email_configs:
      - smarthost: 192.168.1.150:8025
        from: 'prometheus@homelab.lan'
        to: 'slack@mailrise.xyz'
        require_tls: false
