services:
  bind:
    image: cytopia/bind:alpine-0.35
    hostname: bind
    restart: always
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_BIND:-1053}:53/tcp"
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_BIND:-1053}:53/udp"
    environment:
      - DEBUG_ENTRYPOINT=${DEBUG_ENTRYPOINT:-2}
      - MAX_CACHE_SIZE=${BIND_MAX_CACHE_SZIE:-90%}
      - DEBUG_ENTRYPOINT=${DEBUG_ENTRYPOINT:-2}
      - MAX_CACHE_SIZE=${BIND_MAX_CACHE_SIZE:-90%}
      - DNS_A=*.${TLD_SUFFIX:-loc}=127.0.0.1,${EXTRA_HOSTS:-}
      - DNS_FORWARDER=${BIND_DNS_RESOLVER:-8.8.8.8,8.8.4.4}
      - DNSSEC_VALIDATE=${BIND_DNSSEC_VALIDATE:-no}
      - TTL_TIME=${BIND_TTL_TIME}
      - REFRESH_TIME=${BIND_REFRESH_TIME}
      - RETRY_TIME=${BIND_RETRY_TIME}
      - EXPIRY_TIME=${BIND_EXPIRY_TIME}
      - MAX_CACHE_TIME=${BIND_MAX_CACHE_TIME}
      - DOCKER_LOGS=${BIND_LOG_DNS_QUERIES}
    dns:
      - 127.0.0.1
    extra_hosts:
      docker.for.lin.host.internal: 172.16.238.1
      docker.for.lin.localhost: 172.16.238.1
      host.docker.internal: host-gateway
    networks:
      app_net:
        ipv4_address: 172.16.238.100
  php:
    build:
      dockerfile: ./php/Dockerfile-Apache
    hostname: php
    env_file:
      - ./.env
    environment:
      - SVCTL_LISTEN_PORT=9001
      - SVCTL_USER=${DEVILBOX_HTTPD_MGMT_USER:-supervisor}
      - SVCTL_PASS=${DEVILBOX_HTTPD_MGMT_PASS:-mypassword}
      - DEBUG_ENTRYPOINT=${DEBUG_ENTRYPOINT:-2}
      - DOCKER_LOGS
      - COMPOSER_MEMORY_LIMIT=-1
      - NEW_UID
      - NEW_GID
      - TIMEZONE
      - ENABLE_MODULES=${PHP_MODULES_ENABLE}
      - DISABLE_MODULES=${PHP_MODULES_DISABLE}
      - ENABLE_MAIL=${PHP_MAIL_CATCH_ALL:-2}
      - FORWARD_PORTS_TO_LOCALHOST=80:httpd:80,443:httpd:443,3306:mysql:3306,5432:pgsql:5432,6379:redis:6379,11211:memcd:11211,27017:mongo:27017
      - MYSQL_BACKUP_USER=root
      - MYSQL_BACKUP_PASS=${MYSQL_ROOT_PASSWORD}
      - MYSQL_BACKUP_HOST=mysql

    dns:
      - 172.16.238.100
    extra_hosts:
      docker.for.lin.host.internal: 172.16.238.1
      docker.for.lin.localhost: 172.16.238.1
      host.docker.internal: host-gateway
    #volumes:
    #  -
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    depends_on:
      - bind
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1