services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  api:
    build:
      dockerfile: ./PHP/Dockerfile-Nginx
    volumes:
      - ./app:/app