version: "3.8"

services:
  api:
    image: registry.itslit/library/api:latest
    networks:
      - traefik_proxy
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"
        - "traefik.http.routers.api.rule=Host(`api.itslit`)"
        - "traefik.http.routers.api.tls=true"
        - "traefik.http.services.api.loadbalancer.server.port=80"
    volumes:
      - /srv/itslit/php/api/src:/var/www/html/api/src
      - /srv/itslit/php/api/Tests:/var/www/html/api/Tests

  gapi:
    image: registry.itslit/library/gapi:latest
    networks:
      - traefik_proxy
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"
        - "traefik.http.routers.gapi.rule=Host(`gapi.itslit`)"
        - "traefik.http.routers.gapi.tls=true"
        - "traefik.http.services.gapi.loadbalancer.server.port=80"
    volumes:
      - /srv/itslit/php/GAPI/src:/var/www/html/gapi/src
      - /srv/itslit/php/GAPI/Tests:/var/www/html/gapi/Tests

  rpgsite:
    image: registry.itslit/library/rpgsite:latest
    networks:
      - traefik_proxy
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"
        - "traefik.http.routers.rpgsite.rule=Host(`rpgsite.itslit`)"
        - "traefik.http.routers.rpgsite.tls=true"
        - "traefik.http.services.rpgsite.loadbalancer.server.port=80"
    volumes:
      - /srv/itslit/php/RPG-Site/src:/var/www/html/rpg/src

  website:
    image: registry.itslit/library/website:latest
    networks:
      - traefik_proxy
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"
        - "traefik.http.routers.website.rule=Host(`site.itslit`)"
        - "traefik.http.routers.website.tls=true"
        - "traefik.http.services.website.loadbalancer.server.port=80"
    volumes:
      - /srv/itslit/php/Website/src:/var/www/html/site/src

  mysql:
    image: registry.itslit/library/mysql:8.0
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password
      - mysql_database
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
    ports:
     - target: 3306
       published: 3306
       protocol: tcp
       mode: host
    command:
      [
        "mysqld",
        "--innodb-file-per-table=1",
        "--innodb-default-row-format=DYNAMIC"
      ]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == growlithe
    volumes:
      - mysqldata:/var/lib/mysql
      - /srv/itslit/mysql/init-sql:/docker-entrypoint-initdb.d/:ro
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    attachable: true
    external: true

volumes:
  mysqldata:

secrets:
  mysql_root_password:
    external: true
  mysql_user:
    external: true
  mysql_password:
    external: true
  mysql_database:
    external: true