version: "3.8"

services:
  api:
    image: registry.itslit/library/api:latest
    networks:
      - traefik_proxy
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"
        - "traefik.http.routers.api.rule=Host(`api.itslit`)"
        - "traefik.http.routers.api.tls=true"
        - "traefik.http.services.api.loadbalancer.server.port=80"
    volumes:
      - /srv/itslit/php/api/:/var/www/html/api/

  gapi:
    image: registry.itslit/library/gapi:latest
    networks:
      - traefik_proxy
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"
        - "traefik.http.routers.gapi.rule=Host(`gapi.itslit`)"
        - "traefik.http.routers.gapi.tls=true"
        - "traefik.http.services.gapi.loadbalancer.server.port=80"
    volumes:
      - /srv/itslit/php/GAPI/:/var/www/html/gapi/

  rpgsite:
    image: registry.itslit/library/rpgsite:latest
    networks:
      - traefik_proxy
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"
        - "traefik.http.routers.rpgsite.rule=Host(`rpgsite.itslit`)"
        - "traefik.http.routers.rpgsite.tls=true"
        - "traefik.http.services.rpgsite.loadbalancer.server.port=80"
    volumes:
      - /srv/itslit/php/RPG-Site/:/var/www/html/rpg/

  website:
    image: registry.itslit/library/website:latest
    networks:
      - traefik_proxy
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"
        - "traefik.http.routers.website.rule=Host(`site.itslit`)"
        - "traefik.http.routers.website.tls=true"
        - "traefik.http.services.website.loadbalancer.server.port=80"
    volumes:
      - /srv/itslit/php/Website/:/var/www/html/site/

  mysql:
    image: registry.itslit/library/mysql:8.0
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password
      - mysql_database
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"
        - "traefik.http.routers.website.rule=Host(`db.itslit`)"
        - "traefik.http.routers.website.tls=true"
        - "traefik.http.services.website.loadbalancer.server.port=3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/init-sql:/docker-entrypoint-initdb.d/:ro
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    attachable: true
    external: true

volumes:
  mysqldata:

secrets:
  mysql_root_password:
    external: true
  mysql_user:
    external: true
  mysql_password:
    external: true
  mysql_database:
    external: true