services:
  vaultwarden:
    image: registry.itslit/vaultwarden/server:latest
    networks:
      - traefik_proxy
    secrets:
      - source: vaultwarden_admin_token
        target: admin_token
    environment:
      ADMIN_TOKEN_FILE: /run/secrets/admin_token
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"
      DOMAIN: "https://vault.itslit"
      ROCKET_PORT: "80"
    volumes:
      - vaultwarden-data:/data 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == arcanine
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_proxy"

        # --- HTTP → HTTPS redirect ---
        - "traefik.http.routers.vaultwarden-insecure.rule=Host(`vault.itslit`)"
        - "traefik.http.routers.vaultwarden-insecure.entrypoints=web"
        - "traefik.http.routers.vaultwarden-insecure.middlewares=test-redirectscheme"

        # --- HTTPS router ---
        - "traefik.http.routers.vaultwarden.rule=Host(`vault.itslit`)"
        - "traefik.http.routers.vaultwarden.entrypoints=websecure"
        - "traefik.http.routers.vaultwarden.middlewares=test-redirectscheme"
        - "traefik.http.routers.vaultwarden.tls=true"

        # --- HTTP to HTTPS redirect middleware ---
        - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
        - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"

        # --- Traefik service ---
        - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

        - "traefik.http.routers.vaultwarden.service=vaultwarden"

    # Vaultwarden logs & data persist
    configs: []  
secrets:
  vaultwarden_admin_token:
    external: true
volumes:
  vaultwarden-data:
    driver: local
networks:
  traefik_proxy:
    attachable: true
    external: true