version: "3.8"

services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    hostname: ns1.itslit
    networks:
      - traefik_proxy
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
    volumes:
      - bind_etc:/etc/bind
      - bind_cache:/var/cache/bind
      - bind_lib:/var/lib/bind
    environment:
      - TZ=UTC
    configs:
      - source: named_conf_local
        target: /etc/bind/named.conf.local
      - source: zone_file
        target: /etc/bind/db.itslit
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 10s

configs:
  named_conf_local:
    file: ./bind/etc/named.conf.local
  zone_file:
    file: ./bind/etc/db.itslit

volumes:
  bind_etc:
    driver: local
  bind_cache:
    driver: local
  bind_lib:
    driver: local

networks:
  traefik_proxy:
    external: true
