version: "3.8"

services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    networks:
      - traefik-public
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - bind_data:/etc/bind
    environment:
      - TZ=UTC
    configs:
      - source: named_conf_local
        target: /etc/bind/named.conf.local
      - source: zone_file
        target: /etc/bind/db.itslit
    deploy:
      placement:
        constraints: [node.role == manager]

  bind-updater:
    image: python:3.12-slim
    command: >
      bash -c "pip install --no-cache-dir docker && python /scripts/docker_bind_updater.py"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - bind_data:/etc/bind
      - ./bind/docker_bind_updater.py:/scripts/docker_bind_updater.py
    networks:
      - traefik-public
    configs:
      - source: updater_script
        target: /scripts/docker_bind_updater.py
    deploy:
      placement:
        constraints: [node.role == manager]

configs:
  named_conf_local:
    file: ./bind/etc/named.conf.local
  zone_file:
    file: ./bind/etc/db.itslit
  updater_script:
    file: ./bind/docker_bind_updater.py

volumes:
  bind_data:

networks:
  traefik-public:
    external: true
