version: "3.8"

services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    networks:
      - traefik-public
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - bind_data:/etc/bind
    environment:
      - TZ=UTC
    configs:
      - source: named_conf_local
        target: /etc/bind/named.conf.local
      - source: zone_file
        target: /etc/bind/db.itslit
    deploy:
      placement:
        constraints: [node.role == manager]

  bind-updater:
    image: ghcr.io/gliderlabs/docker-gen:latest
    command: -watch -notify "bash /scripts/update-dns.sh" /templates/hosts.tmpl /tmp/hosts.txt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - bind_scripts:/scripts
      - bind_data:/etc/bind
    networks:
      - traefik-public
    configs:
      - source: update_script
        target: /scripts/update-dns.sh
      - source: hosts_template
        target: /templates/hosts.tmpl
    deploy:
      placement:
        constraints: [node.role == manager]

configs:
  named_conf_local:
    file: ./bind/etc/named.conf.local
  zone_file:
    file: ./bind/etc/db.itslit
  update_script:
    file: ./bind/update-dns.sh
  hosts_template:
    file: ./bind/hosts.tmpl

volumes:
  bind_data:
  bind_scripts:

networks:
  traefik-public:
    external: true