global:
  scrape_interval: 60s # How frequently to scrape targets by default.
  scrape_timeout: 10s # How long until a scrape request times out.
  evaluation_interval: 60s # How frequently to evaluate rules.

# A scrape configuration
scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.1.150:8080']
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.1.150:9100']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
