FROM php:7.4-apache

WORKDIR /var/www/html

RUN docker-php-ext-install mysqli pdo pdo_mysql && chown -R www-data:www-data /var/www/html && a2enmod rewrite && apt-get update && apt-get install -y \
    git \
    zip \
    p7zip-full

RUN git clone https://github.com/ItsLit-Media-and-Development/api.git

ENV COMPOSER_ALLOW_SUPERUSER=1
ENV APACHE_DOCUMENT_ROOT=/var/www/html/api/src
COPY --from=composer:2.4 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html/api
RUN composer install --prefer-dist --no-dev --no-scripts --no-progress --no-interaction
RUN composer dump-autoload --optimize

EXPOSE 80