entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: default

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  default:
    files:
      certs:
        - certFile: "/certs/selfsigned.crt"
          keyFile: "/certs/selfsigned.key"