FROM ghcr.io/myoung34/docker-github-actions-runner:latest

ENTRYPOINT ["/bin/bash", "-lc", " \
  if [ -f /run/secrets/gh_actions_pat ]; then \
    export ACCESS_TOKEN=$(cat /run/secrets/gh_actions_pat); \
  fi; \
  exec /entrypoint.sh \
"]