version: "3.8"

services:
  github-runner:
    image: ghcr.io/actions/actions-runner:latest
    environment:
      RUNNER_NAME: "swarm-runner"
      RUNNER_GROUP: "swarm"
      RUNNER_WORKDIR: "/runner/_work"
      REPO_URL: "https://github.com/MarcTowler"
      RUNNER_TOKEN_FILE: "/run/secrets/github_runner_token"

      # Optional: add labels to target workflows
      RUNNER_LABELS: "swarm,docker,local-registry"
    networks:
      - traefik-public
    secrets:
      - github_runner_token
    volumes:
      - runner-data:/runner
      - /var/run/docker.sock:/var/run/docker.sock
      # This is NOT needed unless you want CA directly inside the container
      # - /etc/docker/certs.d:/etc/docker/certs.d:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=false

volumes:
  runner-data:

secrets:
  github_runner_token:
    external: true

networks:
  traefik-public:
    external: true
