version: "3.8"

services:
  kitchenowl:
    image: tombursch/kitchenowl:latest
    environment:
      - TZ=Europe/London
    networks:
      - traefik_proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`meals.itslit`)"
        - "traefik.http.routers.whoami.entrypoints=web,websecure"

networks:
  traefik_proxy:
    driver: overlay
    attachable: true
