version: "3.8"

secrets:
  gh_pat_org:
    external: true
  gh_pat_personal:
    external: true

services:
  runner_org:
    image: registry.itslit/library/github-runner:latest
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
    environment:
      GH_SCOPE: "org"
      GH_OWNER: "ItsLit-Media-and-Development"
      GH_RUNNER_NAME_PREFIX: "itslit-org"
      GH_LABELS: "self-hosted,swarm,org"
      GH_RUNNER_GROUP: "ContainerRunners"
      GH_PAT_FILE: "/run/secrets/gh_pat"
    secrets:
      - source: gh_pat_org
        target: gh_pat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runner_personal:
    image: registry.itslit/library/github-runner:latest
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
    environment:
      GH_SCOPE: "repo"             # personal repo runner
      GH_OWNER: "MarcTowler" # <--- change this
      GH_REPOSITORY: "Docker"   # <--- or template per stack if needed
      GH_RUNNER_NAME_PREFIX: "itslit-personal"
      GH_LABELS: "self-hosted,swarm,personal"
      GH_RUNNER_GROUP: "ContainerRunners"
      GH_PAT_FILE: "/run/secrets/gh_pat"
    secrets:
      - source: gh_pat_personal
        target: gh_pat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    driver: overlay
