version: "3.9"

services:

  # ------------------------------------------------------------
  # Radarr
  # ------------------------------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - traefik_proxy
      - arr-backend
    volumes:
      - /data/apps/radarr/config:/config
      - /data/media/movies:/movies
      - /data/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7878/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.radarr.rule=Host(`radarr.itslit`)"
        - "traefik.http.routers.radarr.entrypoints=websecure"
        - "traefik.http.services.radarr.loadbalancer.server.port=7878"


  # ------------------------------------------------------------
  # Sonarr
  # ------------------------------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    networks:
      - traefik_proxy
      - arr-backend
    volumes:
      - /data/apps/sonarr/config:/config
      - /data/media/tv:/tv
      - /data/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8989/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sonarr.rule=Host(`sonarr.itslit`)"
        - "traefik.http.routers.sonarr.entrypoints=websecure"
        - "traefik.http.services.sonarr.loadbalancer.server.port=8989"


  # ------------------------------------------------------------
  # Lidarr
  # ------------------------------------------------------------
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    networks:
      - traefik_proxy
      - arr-backend
    volumes:
      - /data/apps/lidarr/config:/config
      - /data/media/music:/music
      - /data/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8686/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.lidarr.rule=Host(`lidarr.itslit`)"
        - "traefik.http.routers.lidarr.entrypoints=websecure"
        - "traefik.http.services.lidarr.loadbalancer.server.port=8686"


  # ------------------------------------------------------------
  # Readarr
  # ------------------------------------------------------------
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    networks:
      - traefik_proxy
      - arr-backend
    volumes:
      - /data/apps/readarr/config:/config
      - /data/media/books:/books
      - /data/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8787/ping || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.readarr.rule=Host(`readarr.itslit`)"
        - "traefik.http.routers.readarr.entrypoints=websecure"
        - "traefik.http.services.readarr.loadbalancer.server.port=8787"


  # ------------------------------------------------------------
  # Prowlarr
  # ------------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    networks:
      - traefik_proxy
      - arr-backend
    volumes:
      - /data/apps/prowlarr/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - LOCALHOST_REWRITE=true
      - SERVARR__API__URL=https://apps.servarr.com/v1
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9696/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_proxy"

        # ROUTING
        - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.itslit`)"
        - "traefik.http.routers.prowlarr.entrypoints=websecure"
        - "traefik.http.routers.prowlarr.service=prowlarr"

        # SERVICE PORT
        - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
        - "traefik.http.services.prowlarr.loadbalancer.server.scheme=http"

        # Required Servarr headers for definitions API
        # - "traefik.http.middlewares.prowlarr-servarr-headers.headers.customrequestheaders.User-Agent=Prowlarr"
        # - "traefik.http.middlewares.prowlarr-servarr-headers.headers.customrequestheaders.X-Servarr-Version=1.0"
        # - "traefik.http.routers.prowlarr.middlewares=prowlarr-servarr-headers"

  # -----------------------------------------------------------
  # FlareSolverr (pinned to arcanine, required by Prowlarr)
  # -----------------------------------------------------------
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    networks:
      - arr-backend
    environment:
      - LOG_LEVEL=info
      - TZ=UTC
    deploy:
      placement:
        constraints:
          - node.hostname == arcanine
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8191/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5


  # ------------------------------------------------------------
  # Bazarr
  # ------------------------------------------------------------
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    networks:
      - traefik_proxy
      - arr-backend
    volumes:
      - /data/apps/bazarr/config:/config
      - /data/media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:6767 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bazarr.rule=Host(`bazarr.itslit`)"
        - "traefik.http.routers.bazarr.entrypoints=websecure"
        - "traefik.http.services.bazarr.loadbalancer.server.port=6767"


  # ------------------------------------------------------------
  # qBittorrent
  # ------------------------------------------------------------
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    networks:
      - traefik_proxy
      - arr-backend
    volumes:
      - /data/apps/qbit/config:/config
      - /data/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8081
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.qbit.rule=Host(`qbit.itslit`)"
        - "traefik.http.routers.qbit.entrypoints=websecure"
        - "traefik.http.services.qbit.loadbalancer.server.port=8081"


  # ------------------------------------------------------------
  # Jellyseerr
  # ------------------------------------------------------------
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    networks:
      - traefik_proxy
      - arr-backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == Arcanine
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.itslit`)"
        - "traefik.http.routers.jellyseerr.entrypoints=websecure"
        - "traefik.http.routers.jellyseerr.tls=true"
        - "traefik.http.routers.jellyseerr.tls.certresolver=selfsigned"
        - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
    volumes:
      - /data/apps/jellyseerr/config:/app/config
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
      - NODE_TLS_REJECT_UNAUTHORIZED=0

# ------------------------------------------------------------
# Networks
# ------------------------------------------------------------
networks:
  traefik_proxy:
    external: true
  arr-backend:
    external: true
